from __future__ import annotations
"""othello_match_runner.py
A small framework to run head‑to‑head Othello/Reversi matches between text‑mode
engines that speak (a subset of) the Go Text Protocol (GTP).

Revision history
----------------
• **2025‑06‑14**   Add `win_to_wsl_path()` helper.
• **2025‑06‑14**   *Fix*: every move generated by one engine is now **mirrored**
  into the opponent via a `play <color> <move>` command so that both engines
  keep an identical board state.

Requirements
------------
• Python ≥ 3.9
• Executable paths supplied via *config.py*::

    leelaz      = "C:/engines/leelaz.exe"
    edax        = "C:/engines/edax.exe"
    kalmia      = "C:/engines/kalmia.exe"
    egaroucid   = "C:/engines/egaroucid.exe"
    rundir       = "C:/tmp/engine_workdir"
    results_root = "C:/tmp/othello_results"
    leelaz_args  = ["-g", "-q"]
    match_args   = ["-g", "-q"]

Edit those paths and the default Leela arguments to suit your setup.
"""

from dataclasses import dataclass, field
from pathlib import Path, PureWindowsPath
from multiprocessing import Pool, cpu_count
from uuid import uuid4
import subprocess
import tarfile
import csv
import hashlib
import os
from typing import List, Tuple, Dict

# ---------------------------------------------------------------------------
# Configuration helpers (imported from user's config.py)
# ---------------------------------------------------------------------------

try:
    from config import (
        leelaz,
        edax,
        kalmia,
        egaroucid,
        rundir,
        results_root,
    )
except ImportError as exc:
    raise RuntimeError("config.py with engine paths is required") from exc

LEELA_DEFAULT_VISITS = 1000  # default visits for Leela
SGF_HEADER = "(;GM[2]FF[4]SZ[8]"
SGF_FOOTER = ")\n"

Path(results_root).mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------------
# Miscellaneous helpers
# ---------------------------------------------------------------------------

def win_to_wsl_path(win_path: str | os.PathLike) -> str:
    """Convert an absolute Windows file‑system path to its WSL counterpart."""
    p = PureWindowsPath(str(win_path))
    if not p.drive:
        raise ValueError(f"Cannot convert relative path '{win_path}'.")
    drive = p.drive.rstrip(":").lower()
    rest = "/".join(p.parts[1:])
    return f"/mnt/{drive}/{rest}"


def send_cmd(proc: subprocess.Popen, cmd: str) -> Tuple[str, List[str]]:
    """Send *one* GTP command and wait for the reply (header + payload)."""
    proc.stdin.write(cmd + "\n")
    proc.stdin.flush()
    # print(cmd + "\n", flush=True)
    header = proc.stdout.readline()
    payload: List[str] = []
    while True:
        line = proc.stdout.readline()
        if line in ("\n", ""):
            break
        payload.append(line.rstrip("\n"))
    return header.lstrip("= ?").strip(), payload


def sha256_short(path: str | Path, n: int = 8) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()[:n]


# ---------------------------------------------------------------------------
# Engine wrapper
# ---------------------------------------------------------------------------

@dataclass
class Engine:
    name: str
    exe: str | Path
    category: str
    extra: List[str] = field(default_factory=list)
    proc: subprocess.Popen | None = field(init=False, default=None)

    def start(self):
        if self.proc is not None:
            return
        self.proc = subprocess.Popen(
            [self.exe, *self.extra],
            cwd=rundir,
            text=True,
            bufsize=1,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            # stderr=subprocess.STDOUT,
        )
        send_cmd(self.proc, "boardsize 8")
        send_cmd(self.proc, "clear_board")

    def restart(self):
        self.close()
        self.start()

    def close(self):
        if self.proc is None:
            return
        try:
            send_cmd(self.proc, "quit")
        except Exception:
            pass
        self.proc.kill()
        self.proc = None

    # ---- gameplay helpers -------------------------------------------------
    def genmove(self, colour: str) -> str:
        header, _ = send_cmd(self.proc, f"genmove {colour}")
        return header.strip()

    def play_move(self, colour: str, move: str):
        send_cmd(self.proc, f"play {colour} {move}")

    def final_score(self) -> str:
        header, _ = send_cmd(self.proc, "final_score")
        return header

    def short(self) -> str:
        return self.name.replace(" ", "_")


class LeelaEngine(Engine):
    def __init__(self, net_path: str | Path, visits: int = LEELA_DEFAULT_VISITS):
        wsl_path = win_to_wsl_path(net_path)
        wsl_path = Path(wsl_path)
        net_hash = sha256_short(wsl_path)
        category = f"leelaz-{net_hash}"
        super().__init__(
            name=f"LeelaZero-{net_hash}",
            exe=leelaz,
            category=category,
            extra=match_args + ["-w", str(net_path), "-v", str(visits)],
        )


class EdaxEngine(Engine):
    def __init__(self):
        super().__init__("edax", edax, "edax")


class KalmiaEngine(Engine):
    def __init__(self):
        super().__init__("kalmia", kalmia, "kalmia")


class EgaroucidEngine(Engine):
    def __init__(self):
        super().__init__("egaroucid", egaroucid, "egaroucid")


# ---------------------------------------------------------------------------
# SGF helpers
# ---------------------------------------------------------------------------

_ALPHA = "abcdefgh"

def coord_to_sgf(m: str) -> str:
    if m.lower() == "pass":
        return ""
    x = _ALPHA.index(m[0].lower())
    y = int(m[1]) - 1
    return f"{_ALPHA[x]}{_ALPHA[y]}"


# ---------------------------------------------------------------------------
# Game driver
# ---------------------------------------------------------------------------

@dataclass
class GameResult:
    moves: int
    res_a: str
    res_b: str
    sgf: Path


class Game:
    def __init__(self, black: Engine, white: Engine, no: int, match_id: str, out_dir: Path):
        self.B = black
        self.W = white
        self.no = no
        self.mid = match_id
        self.out = out_dir

    def _sgf(self, seq, res_tag):
        parts = [SGF_HEADER, f"PB[{self.B.name}]", f"PW[{self.W.name}]", f"RE[{res_tag}]"]
        for col, mv in seq:
            if mv.lower() == "resign":
                continue
            parts.append(f";{col}[{coord_to_sgf(mv)}]")
        parts.append(SGF_FOOTER)
        return "".join(parts)

    def play(self) -> GameResult:
        # fresh engines
        self.B.restart()
        self.W.restart()

        history = []  # ("B"|"W", move)
        to_move = "black"
        passes = 0
        moves = 0
        resigned = False

        while True:
            eng = self.B if to_move == "black" else self.W
            opp = self.W if to_move == "black" else self.B

            mv = eng.genmove(to_move)
            moves += 1
            history.append(("B" if to_move == "black" else "W", mv))

            lo = mv.lower()
            # mirror the move to the opponent so its board state matches
            if lo == "pass":
                opp.play_move(to_move, "pass")
            elif lo != "resign":
                opp.play_move(to_move, mv)

            if lo == "resign":
                resigned = True
                break
            if lo == "pass":
                passes += 1
                if passes == 2:
                    break
            else:
                passes = 0

            to_move = "white" if to_move == "black" else "black"

        if resigned:
            res_a = res_b = "W+R" if to_move == "black" else "B+R"
        else:
            res_a = self.B.final_score()
            res_b = self.W.final_score()

        sgf_txt = self._sgf(history, res_a)
        fn = f"{self.mid}_g{self.no:03d}_{self.B.short()}-B_{self.W.short()}-W.sgf"
        fp = self.out / fn
        with open(fp, "w", encoding="utf-8") as f:
            f.write(sgf_txt)

        self.B.close()
        self.W.close()
        return GameResult(moves, res_a, res_b, fp)


# ---------------------------------------------------------------------------
# Match driver
# ---------------------------------------------------------------------------

@dataclass
class MatchRunner:
    A: Engine
    B: Engine
    games: int = 100
    root: Path = Path(results_root)

    def run(self) -> Tuple[str, List[Dict]]:
        assert self.games % 2 == 0, "games must be even"
        mid = uuid4().hex[:8]
        tmp = self.root / "tmp" / mid
        tmp.mkdir(parents=True, exist_ok=True)

        print(f"Starting match {mid}")
        rows: List[Dict] = []
        for g in range(self.games):
            blk, wht = (self.A, self.B) if g % 2 == 0 else (self.B, self.A)
            result = Game(blk, wht, g + 1, mid, tmp).play()
            winner = blk.name if result.res_a.startswith('B') else wht.name
            print(f"Game {g+1} won by {winner} with score {result.res_a}")
            rows.append({
                "match_id": mid,
                "game_no": g + 1,
                "black": blk.name,
                "white": wht.name,
                f"{self.A.name}_result": result.res_a,
                f"{self.B.name}_result": result.res_b,
                "move_count": result.moves,
                "sgf_file": result.sgf.name,
            })

        # tar.gz of SGFs copied under both categories
        tar_name = f"match_{mid}.tar.gz"
        tar_tmp = tmp.parent / tar_name
        with tarfile.open(tar_tmp, "w:gz") as tar:
            for f in tmp.glob("*.sgf"):
                tar.add(f, arcname=f.name)

        for cat in (self.A.category, self.B.category):
            dest = self.root / cat
            dest.mkdir(parents=True, exist_ok=True)
            (dest / tar_name).write_bytes(tar_tmp.read_bytes())

        # clean tmp
        for f in tmp.glob("*"):
            f.unlink()
        tmp.rmdir()

        return mid, rows


# ---------------------------------------------------------------------------
# Batch helper
# ---------------------------------------------------------------------------

def _work(spec):
    A, B, n, r = spec
    mid, rows = MatchRunner(A, B, n, Path(r)).run()
    return rows


def run_batch(pairs: List[Tuple[Engine, Engine]], games: int = 100, workers: int = 1, csv_out: str | Path | None = None):
    if csv_out is None:
        csv_out = Path(results_root) / "results.csv"

    specs = [(a, b, games, str(results_root)) for a, b in pairs]
    all_rows: List[Dict] = []

    if workers == 1:
        for s in specs:
            all_rows.extend(_work(s))
    else:
        with Pool(min(cpu_count(), workers)) as pool:
            for rows in pool.imap_unordered(_work, specs):
                all_rows.extend(rows)

    # write CSV
    fields = [
        "match_id", "game_no", "black", "white",
        *sorted({k for r in all_rows for k in r if k.endswith("_result")}),
        "move_count", "sgf_file",
    ]
    with open(csv_out, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(all_rows)

    print(f"Batch finished – csv saved to {csv_out}")


# ---------------------------------------------------------------------------
# Demo
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    from config import *

    leela1  = LeelaEngine(save_gen_dir_ + "\\1\\leelaz-model-4000.txt.gz")
    leela4  = LeelaEngine(save_gen_dir_ + "\\4\\leelaz-model-16000.txt.gz")
    leela15 = LeelaEngine(save_gen_dir_ + "\\15\\leelaz-model-60000.txt.gz")
    leela58 = LeelaEngine(save_gen_dir_ + "\\58\\leelaz-model-232000.txt.gz")
    # edax_engine = EdaxEngine()

    run_batch([
        (leela15, leela4)
    ], games=10, workers=2)
